### ISSUE TITLE
Back from Settings -> App crash

### ISSUE THREAD

**Issue by hash13** [Qabel/qabel-android#585]
Click on Settings in Sidemenu and follow with back in nav bar or with hardware back key crashs app

Exception: Receiver not registered

/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: de.qabel.qabel, PID: 21185
                                                   **java.lang.RuntimeException: Unable to destroy activity {de.qabel.qabel/de.qabel.qabelbox.settings.SettingsActivity}: java.lang.IllegalArgumentException: Receiver not registered: de.qabel.qabelbox.settings.fragments.SettingsFragmen**t$1@16ee816f
                                                       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3916)
                                                       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3934)
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:151)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5499)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)
                                                    **Caused by: java.lang.IllegalArgumentException: Receiver not registered: de.qabel.qabelbox.settings.fragments.SettingsFragmen**t$1@16ee816f
                                                       at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:783)
                                                       at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1666)
                                                       at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:511)
                                                       at de.qabel.qabelbox.settings.fragments.SettingsFragment.onDetach(SettingsFragment.java:85)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1021)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                       at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1049)
                                                       at android.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:1897)
                                                       at android.app.Activity.performDestroy(Activity.java:6168)
                                                       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1157)
                                                       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3896)
                                                       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3934) 
                                                       at android.app.ActivityThread.access$1400(ActivityThread.java:151) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1408) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:135) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5499) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by hash13** [comment]
maybe same bug as issue #587

**Comment by audax** [comment]
Resolved in /master

**Comment by JoGir** [comment]
Still broken. Change broadcaseReceiver handling to resume/pause...
